---
- name: network-scripts | Deploy ifup-local
  template:
    src: "ifup_local.j2"
    dest: "{{ hostvars[inventory_hostname]['network_scripts_triggers_dest'] + '/' + vars['trigger_type'] + '-local' }}"
    group: "root"
    owner: "root"
    mode: "0755"
  vars:
    trigger_type: 'ifup'
- name: network-scripts | Deploy ifdown-local
  template:
    src: "ifdown_local.j2"
    dest: "{{ hostvars[inventory_hostname]['network_scripts_triggers_dest'] + '/' + vars['trigger_type'] + '-local' }}"
    group: "root"
    owner: "root"
    mode: "0755"
  vars:
    trigger_type: 'ifdown'
