---
- name: network-scripts | Add the OS specific variables
  include_vars: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: network-scripts | Deploy global settings
  template:
    src: "network_global.j2"
    dest: "{{ hostvars[inventory_hostname]['network_scripts_sysconfig_dest'] + '/' + 'network' }}"
    group: "root"
    owner: "root"
    mode: "0644"
