---
- name: "{{ 'network-scripts | Deploy ' + vars['trigger_type'] + '-local' }}"
  ansible.builtin.template:
    src: "{{ vars['trigger_type'] + '_local' + '.j2' }}"
    dest: "{{ hostvars[inventory_hostname]['network_scripts_triggers_dest'] +
      '/' + vars['trigger_type'] + '-local' }}"
    group: "root"
    owner: "root"
    force: "yes"
    mode: "0755"
  vars:
    trigger_type: 'ifup'
- name: "{{ 'network-scripts | Deploy ' + vars['trigger_type'] + '-local' }}"
  ansible.builtin.template:
    src: "{{ vars['trigger_type'] + '_local' + '.j2' }}"
    dest: "{{ hostvars[inventory_hostname]['network_scripts_triggers_dest'] +
      '/' + vars['trigger_type'] + '-local' }}"
    group: "root"
    owner: "root"
    force: "yes"
    mode: "0755"
  vars:
    trigger_type: 'ifdown'
