---
- include: pre_requisite.yml
- include: deploy_global.yml
  when:
  - "hostvars[inventory_hostname]['network_scripts_global'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_global'] != ''"
  - "hostvars[inventory_hostname]['network_scripts_deploy_global'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_deploy_global'] == 'true'"
- include: interface_executor.yml
  when:
  - "vars['network_interfaces'] is defined"
- include: deploy_ppp.yml
  when:
  - "hostvars[inventory_hostname]['network_scripts_interfaces'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_interfaces'] != ''"
- include: deploy_triggers.yml
  when:
  - "hostvars[inventory_hostname]['network_scripts_interfaces'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_interfaces'] != ''"
  - "hostvars[inventory_hostname]['network_scripts_deploy_triggers'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_deploy_triggers'] == 'true'"
