---
- name: network-scripts | Add the OS specific variables
  include_vars: "{{
    hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: network-scripts | Set facts about interfaces
  set_fact:
    network_interfaces: "{{
      hostvars[inventory_hostname]['network_scripts_interfaces'] |
      json_query('[].interface') }}"
  when:
  - "hostvars[inventory_hostname]['network_scripts_interfaces'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_interfaces'] != ''"
- name: network-scripts | Find exists network profiles
  find:
    paths: "{{ hostvars[inventory_hostname]['network_scripts_sysconfig_dest'] +
      '/' + 'network-scripts' }}"
    recurse: "no"
    file_type: "file"
    patterns: "^ifcfg-(.*)"
    use_regex: "true"
  register: "find_result"
  when:
  - "hostvars[inventory_hostname]['network_scripts_drop_exists'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_drop_exists'] == 'true'"
- name: network-scripts | Delete exists network profiles
  file:
    path: "{{ item.path }}"
    state: "absent"
  loop: "{{ vars['find_result']['files'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.path }}"
  when:
  - "vars['find_result']['files'] is defined"
