---
- name: Enable network service
  service:
    name: "{{ hostvars[inventory_hostname]['network_scripts_service'] }}"
    enabled: "yes"
  when:
  - "hostvars[inventory_hostname]['network_scripts_enable'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_enable'] == 'true'"
- name: Restart network service
  service:
    name: "{{ hostvars[inventory_hostname]['quagga_zebra_service'] }}"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['network_scripts_restart'] is defined"
  - "hostvars[inventory_hostname]['network_scripts_restart'] == 'true'"
